[package]
name = "comment_away_lib"
version = "0.1.0"
edition = "2021"
[dependencies]
tree-sitter = "0.24.4"
libloading = "0.8.5"
anyhow = "1.0.93"
object = "0.36.5"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0"
